### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by jorbuedo** [tw-in-js/example-wmr#1]
Hi! I was trying this integration between wmr and twind, sadly it doesn't build. Dev run fine, but build throws this error:

`Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:756:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36)
error Command failed with exit code 1.`

If it helps, node version is: v14.12.0

Any idea how to solve this? Many thanks.

**Comment by jorbuedo** [comment]
Nevermind, I found the related issue in wmr: https://github.com/preactjs/wmr/issues/308
